# Generated by Django 3.0.1 on 2019-12-19 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementsofcashflows',
            name='date_pulled',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 13, 2, 11, 568448)),
        ),
    ]
