# Generated by Django 3.0.1 on 2019-12-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flows', '0002_statementsofcashflows_date_pulled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementsofcashflows',
            name='date_pulled',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
